# Generated by Django 5.0 on 2024-06-12 20:44

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('TitleName', models.CharField(max_length=30)),
                ('HasPassport', models.BooleanField()),
                ('Salary', models.IntegerField()),
                ('BirthDate', models.DateField()),
                ('HireDate', models.DateField()),
                ('Notes', models.CharField(max_length=200)),
                ('Country', models.CharField(choices=[('IND', 'INDIA'), ('USA', 'United States Of America'), ('UK', 'United Kingdom'), ('AUS', 'AUSTRAlIA'), ('AU', 'AUSTRIA'), ('SP', 'SPAINj')], default=None, max_length=35)),
            ],
        ),
    ]
