# Generated by Django 5.0 on 2024-06-12 21:03

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('PayRollApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Country',
            field=models.CharField(choices=[('IND', 'INDIA'), ('USA', 'United States Of America'), ('UK', 'United Kingdom'), ('AUS', 'AUSTRAlIA'), ('AU', 'AUSTRIA'), ('SP', 'SPAIN')], default=None, max_length=35),
        ),
    ]
