# Generated by Django 5.0 on 2024-06-12 21:09

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('PayRollApp', '0002_AddingEmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='PhoneNumber',
            field=models.CharField(default='', max_length=20),
        ),
    ]
